### PR TITLE
Refactor/update abi files

### PR DESCRIPTION
**Pull request by adam-arold**
In this PR I've added the relevant ABI files to a workspace library together with the corresponding typechain generation step.

### CODE REVIEW

**Review by jordaniza — COMMENTED** [review]
My understanding is that the present bash script can be invoked with `typechain`. I can't see exactly how to do this in the repo - either in the readme or a package.json or an Nx script - can you clarify?

**Comment by adam-arold** [comment]
> Please check the conflicts on this

Fixed it!

**Comment by adam-arold** [comment]
> My understanding is that the present bash script can be invoked with `typechain`. I can't see exactly how to do this in the repo - either in the readme or a package.json or an Nx script - can you clarify?

I've added the necessary info to the setup part of the README.

**Review by gbonumore — APPROVED** [review]

**Review by jordaniza — APPROVED** [review]
Thanks for adding the changes

**Pull request merged**
